config/routes.rb
Rails.application.routes.draw do
  resources :tarefas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tarefa.rb
class Tarefa < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController
  before_action :set_tarefa, only: %i[ show edit update destroy ]

  # GET /tarefas or /tarefas.json
  def index
    @tarefas = Tarefa.all
  end

  # GET /tarefas/1 or /tarefas/1.json
  def show
  end

  # GET /tarefas/new
  def new
    @tarefa = Tarefa.new
  end

  # GET /tarefas/1/edit
  def edit
  end

  # POST /tarefas or /tarefas.json
  def create
    @tarefa = Tarefa.new(tarefa_params)

    respond_to do |format|
      if @tarefa.save
        format.html { redirect_to tarefa_url(@tarefa), notice: "Tarefa was successfully created." }
        format.json { render :show, status: :created, location: @tarefa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tarefas/1 or /tarefas/1.json
  def update
    respond_to do |format|
      if @tarefa.update(tarefa_params)
        format.html { redirect_to tarefa_url(@tarefa), notice: "Tarefa was successfully updated." }
        format.json { render :show, status: :ok, location: @tarefa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tarefas/1 or /tarefas/1.json
  def destroy
    @tarefa.destroy!

    respond_to do |format|
      format.html { redirect_to tarefas_url, notice: "Tarefa was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarefa
      @tarefa = Tarefa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tarefa_params
      params.require(:tarefa).permit(:nome, :resolvida)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tarefas_helper.rb
module TarefasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ListaDeTarefas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tarefas/_form.html.erb
<%= form_with(model: tarefa) do |form| %>
  <% if tarefa.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tarefa.errors.count, "error") %> prohibited this tarefa from being saved:</h2>

      <ul>
        <% tarefa.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :resolvida, style: "display: block" %>
    <%= form.check_box :resolvida %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tarefas/_tarefa.html.erb
<div id="<%= dom_id tarefa %>">
  <p>
    <strong>Nome:</strong>
    <%= tarefa.nome %>
  </p>

  <p>
    <strong>Resolvida:</strong>
    <%= tarefa.resolvida %>
  </p>

</div>

app/views/tarefas/edit.html.erb
<h1>Editing tarefa</h1>

<%= render "form", tarefa: @tarefa %>

<br>

<div>
  <%= link_to "Show this tarefa", @tarefa %> |
  <%= link_to "Back to tarefas", tarefas_path %>
</div>

app/views/tarefas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tarefas</h1>

<div id="tarefas">
  <% @tarefas.each do |tarefa| %>
    <%= render tarefa %>
    <p>
      <%= link_to "Show this tarefa", tarefa %>
    </p>
  <% end %>
</div>

<%= link_to "New tarefa", new_tarefa_path %>

app/views/tarefas/new.html.erb
<h1>New tarefa</h1>

<%= render "form", tarefa: @tarefa %>

<br>

<div>
  <%= link_to "Back to tarefas", tarefas_path %>
</div>

app/views/tarefas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tarefa %>

<div>
  <%= link_to "Edit this tarefa", edit_tarefa_path(@tarefa) %> |
  <%= link_to "Back to tarefas", tarefas_path %>

  <%= button_to "Destroy this tarefa", @tarefa, method: :delete %>
</div>